# Generated by Django 4.0.4 on 2022-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=255)),
                ('cpf', models.CharField(db_column='CPF', max_length=11)),
                ('cargo', models.CharField(db_column='CARGO', max_length=255)),
            ],
            options={
                'db_table': 'FUNCIONARIO',
            },
        ),
    ]
