# Generated by Django 4.0.4 on 2022-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.FloatField(db_column='SALARIO', default=0.0),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(db_column='CPF', max_length=11, unique=True),
        ),
    ]
