# Generated by Django 4.0.4 on 2022-05-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_funcionario_salario_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=255)),
                ('numero', models.IntegerField(db_column='NUMERO', unique=True)),
                ('preco', models.FloatField(db_column='PRECO', default=0.0)),
            ],
            options={
                'db_table': 'Produtos',
            },
        ),
    ]
